### PR TITLE
fix: allow pnpm workspace aliases

### LINKED ISSUE #389: 🐛 Bug: support "referencing workspace packages through aliases"
### Bug Report Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have pulled the latest `main` branch of the repository.
- [x] I have [searched for related issues](https://github.com/JoshuaKGoldberg/package-json-validator/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Should allow [referencing workspace packages through aliases](https://pnpm.io/workspaces#referencing-workspace-packages-through-aliases) as valid.

### Actual

```
Invalid devDependencies: invalid version range for dependency @types/eslint-community__eslint-plugin-eslint-comments: workspace:@eslint-deputy/types___eslint-community__eslint-plugin-eslint-comments@*eslint(package-json/valid-devDependencies)
```

### Additional Info

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/1210

### PR DESCRIPTION
**Pull request by lishaduck**
## PR Checklist

- [x] Addresses an existing open issue: fixes #389
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/package-json-validator/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/package-json-validator/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Embedded the package regex inside of the version regex for an _even longer_ mess.
(Looking at all the regexes made me sad. Why can't TC39 just standardize parser combinators? :P)

And thanks for maintaining this! I know I'd probably have given up pretty quickly if it fell on me to maintain a library of regexes.

 💖

### CODE REVIEW

**Comment by lishaduck** [comment]
Oooh! PR #400!

(Sorry, just love zero-suffixed items)

File: src/validators/validateDependencies.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ const isUnpublishedVersion = (version: string): boolean => {
 			version,
 		) ||
 		// https://pnpm.io/next/workspaces#workspace-protocol-workspace
-		/^workspace:((\^|~)?[0-9.x]*|(<=?|>=?)?[0-9.x][\-.+\w]+|\*)?$/.test(
+		/^workspace:([a-z0-9@/][\w@/.\-]*@)?((\^|~)?[0-9.x]*|(<=?|>=?)?[0-9.x][\-.+\w]+|\*)?$/.test(
```
Comment (michaelfaith) [inline src/validators/validateDependencies.ts]: 🤔 I wonder if we should just allow anything after `workspace:` at this point, like we do with `npm:` the next condition down, rather than trying to craft a super specific regex?

**Review by michaelfaith — COMMENTED** [review]
Thanks for taking this up!  Looks like there's an outstanding lint error (you can run `pnpm lint` locally, if you want to test it again after you've made an update to it).  
Other than that, I'm wondering if maybe we should err on the side of relaxing validation on `workspace:` protocol even more, like we did with `npm:`?

**Comment by lishaduck** [comment]
> Thanks for taking this up! Looks like there's an outstanding lint error (you can run `pnpm lint` locally, if you want to test it again after you've made an update to it). 

Yup, I fixed it locally, but it looks like lint-staged doesn't work on windows or something?
I'm getting this:
```
[info] node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises
    at new NodeError (node:internal/errors:371:5)
    at ESMLoader.builtinStrategy (node:internal/modules/esm/translators:276:11)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
    at async link (node:internal/modules/esm/module_job:67:21) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
husky - pre-commit script failed (code 1)
```

I'm just using `--no-verify`, but that's probably prohibitive to most potential contributors who'd hit that.

> Other than that, I'm wondering if maybe we should err on the side of relaxing validation on `workspace:` protocol even more, like we did with `npm:`?

Never! lol
I mean, why did we do that to npm? Is there history? Just that it's complicated?

**Comment by lishaduck** [comment]
> Yup, I fixed it locally, but it looks like lint-staged doesn't work on windows or something?

`node:readline/promises` works on all platforms and is included since v17... so IDK, something must be messed up 🤷🏻‍♂️

**Comment by michaelfaith** [comment]
> Yup, I fixed it locally, but it looks like lint-staged doesn't work on windows or something? I'm getting this:

I'm using windows, and haven't encountered that.  What version of node are you using?

**Comment by lishaduck** [comment]
> > Yup, I fixed it locally, but it looks like lint-staged doesn't work on windows or something? I'm getting this:
> 
> I'm using windows, and haven't encountered that. What version of node are you using?

Should be Node 24.5, but idk what vscode is picking up.

File: src/validators/validateDependencies.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply src/validators/validateDependencies.ts]: Yeah 😬 this is looking very difficult to maintain. And honestly already was.

**Comment by JoshuaKGoldberg** [comment]
> `No such built-in module: node:readline/promises`

You must be on a very old version of Node.js. `node:readline/promises` dates back to https://nodejs.org/en/blog/release/v17.0.0#readline-promise-api.

**Comment by lishaduck** [comment]
> > `No such built-in module: node:readline/promises`
> 
> You must be on a very old version of Node.js. `node:readline/promises` dates back to [nodejs.org/en/blog/release/v17.0.0#readline-promise-api](https://nodejs.org/en/blog/release/v17.0.0#readline-promise-api).

As I said, it should be 24.5, but it wouldn't surprise me if vs code is picking the wrong node.

**Comment by lishaduck** [comment]
> > > `No such built-in module: node:readline/promises`
> > 
> > 
> > You must be on a very old version of Node.js. `node:readline/promises` dates back to [nodejs.org/en/blog/release/v17.0.0#readline-promise-api](https://nodejs.org/en/blog/release/v17.0.0#readline-promise-api).
> 
> As I said, it should be 24.5, but it wouldn't surprise me if vs code is picking the wrong node.

Ha. `C:\Program Files\nodejs\node.EXE` is still at `v16.13.1` 🤦🏻‍♂️

I remember those days... back when 14 was lts, and 16 was current... ah it's been a long time lol

**Review by michaelfaith — APPROVED** [review]
Looks good. Thanks!

**Comment by michaelfaith** [comment]
@all-contributors please add @lishaduck for code
